ns_basetheme.website.settings.footer_menu: 7
ns_basetheme.website.settings.main_menu: 10
ns_basetheme.website.settings.style_theme_color: valueA
ns_basetheme.website.settings.googleanalyticsstatus: true
ns_basetheme.website.settings.back_to_top: true
copyright: copyright@2025
ns_basetheme.website.settings.compress_cssjs: true
